@extends('layouts.workspace', ['navActive' => 'admin-system'])
@section('title', $user->publicName())
@section('page-title', $user->publicName())
@section('page-context', '@'.$user->username.' · '.$user->email)
@section('page-actions')<a href="{{ route('user.show', $user->profileRouteKey()) }}" class="rounded-lg border border-ink-200 px-3 py-2 text-sm font-bold dark:border-ink-700 dark:text-white">{{ __('user.public_profile') }}</a>@endsection
@section('content')
<div class="mx-auto max-w-6xl space-y-6">@if(session('status'))<p class="rounded-xl border border-leaf-200 bg-leaf-50 px-4 py-3 text-sm font-bold text-leaf-800 dark:border-leaf-800 dark:bg-leaf-950 dark:text-leaf-300">{{ session('status') }}</p>@endif
<div class="grid gap-6 lg:grid-cols-2">
<section class="rounded-2xl border border-ink-100 bg-white p-6 dark:border-ink-800 dark:bg-ink-900"><h2 class="text-lg font-black dark:text-white">{{ __('user.account_status') }}</h2><dl class="mt-4 grid grid-cols-2 gap-3 text-sm"><div><dt class="font-bold text-ink-500">{{ __('user.account') }}</dt><dd class="mt-1"><span class="inline-flex items-center rounded-md px-2.5 py-0.5 text-xs font-bold {{ $user->accountStatusBadgeClass() }}">{{ $user->accountStatusLabel() }}</span></dd></div><div><dt class="font-bold text-ink-500">{{ __('user.membership') }}</dt><dd class="mt-1"><span class="inline-flex items-center rounded-md px-2.5 py-0.5 text-xs font-bold {{ $user->membershipStatusBadgeClass() }}">{{ $user->membershipStatusLabel() }}</span></dd></div></dl>@if(!auth()->user()->is($user))<form method="post" action="{{ route('workspace.system.user.status', $user) }}" class="mt-5 space-y-3">@csrf @method('put')<select name="status_account" class="w-full rounded-xl border border-ink-200 px-3 py-2 dark:border-ink-700 dark:bg-ink-950 dark:text-white"><option value="ACT">{{ __('user.activate') }}</option><option value="SUS">{{ __('user.suspend') }}</option></select><textarea name="reason" required minlength="10" maxlength="500" placeholder="{{ __('user.reason_required') }}" class="w-full rounded-xl border border-ink-200 px-3 py-2 dark:border-ink-700 dark:bg-ink-950 dark:text-white"></textarea><button class="rounded-lg bg-ember-500 px-4 py-2 text-sm font-bold text-white">{{ __('user.update_status') }}</button></form>@else<p class="mt-4 text-sm text-ink-500">{{ __('user.self_status_guard') }}</p>@endif</section>
<section class="rounded-2xl border border-ink-100 bg-white p-6 dark:border-ink-800 dark:bg-ink-900"><h2 class="text-lg font-black dark:text-white">{{ __('user.assign_role') }}</h2><form method="post" action="{{ route('workspace.system.user.access.store', $user) }}" class="mt-4 space-y-3">@csrf<select name="role_workspace" class="w-full rounded-xl border border-ink-200 px-3 py-2 dark:border-ink-700 dark:bg-ink-950 dark:text-white">@foreach(config('user.role_labels') as $code=>$label)<option value="{{ $code }}">{{ $label }}</option>@endforeach</select><label class="flex gap-2 text-sm dark:text-white"><input type="checkbox" name="is_role_public" value="1" class="size-4 accent-ember-500">{{ __('user.show_role_publicly') }}</label><textarea name="grant_reason" required minlength="10" maxlength="500" placeholder="{{ __('user.reason_required') }}" class="w-full rounded-xl border border-ink-200 px-3 py-2 dark:border-ink-700 dark:bg-ink-950 dark:text-white"></textarea><button class="rounded-lg bg-ink-950 px-4 py-2 text-sm font-bold text-white dark:bg-ember-500">{{ __('user.assign_role') }}</button></form></section>
</div>
<section class="rounded-2xl border border-ink-100 bg-white p-6 dark:border-ink-800 dark:bg-ink-900"><h2 class="text-lg font-black dark:text-white">{{ __('user.access_assignments') }}</h2><ul class="mt-4 divide-y divide-ink-100 dark:divide-ink-800">@forelse($assignments as $assignment)<li class="py-4"><div class="flex flex-wrap items-start justify-between gap-4"><div><p class="font-bold dark:text-white">{{ config('user.role_labels.'.$assignment->role_workspace, $assignment->role_workspace) }} <span class="text-xs text-ink-500">{{ $assignment->status_user_access }}</span></p><p class="text-xs text-ink-500">{{ $assignment->scope_access }} · {{ $assignment->grant_reason }}</p></div>@if($assignment->status_user_access==='ACT')<form method="post" action="{{ route('workspace.system.user.access.destroy', [$user,$assignment]) }}" class="flex gap-2">@csrf @method('delete')<input name="revocation_reason" required minlength="10" maxlength="500" placeholder="{{ __('user.revocation_reason') }}" class="rounded-lg border border-ink-200 px-3 py-2 text-sm dark:border-ink-700 dark:bg-ink-950 dark:text-white"><button class="text-sm font-bold text-ember-700 dark:text-ember-300">{{ __('user.revoke') }}</button></form>@endif</div></li>@empty<li class="py-4 text-sm text-ink-500">{{ __('user.no_access') }}</li>@endforelse</ul></section>
<section class="rounded-2xl border border-ink-100 bg-white p-6 dark:border-ink-800 dark:bg-ink-900"><h2 class="text-lg font-black dark:text-white">{{ __('user.sessions') }}</h2><ul class="mt-4 divide-y divide-ink-100 dark:divide-ink-800">@forelse($sessions as $session)<li class="flex items-center justify-between gap-4 py-4"><div><p class="font-bold dark:text-white">{{ $session->user_agent_summary }}</p><p class="text-xs text-ink-500">{{ $session->status_user_session }} · {{ optional($session->last_activity_at)->diffForHumans() }}</p></div>@if($session->status_user_session==='ACT')<form method="post" action="{{ route('workspace.system.user.session.destroy', [$user,$session]) }}">@csrf @method('delete')<button class="text-sm font-bold text-ember-700 dark:text-ember-300">{{ __('user.sign_out') }}</button></form>@endif</li>@empty<li class="py-4 text-sm text-ink-500">{{ __('user.no_tracked_sessions') }}</li>@endforelse</ul></section>
</div>
@endsection
