<?php
/**
 * Field-name index tool.
 *
 * Build mode (default) — regenerate data/field_index.txt:
 *   php tools/script/build_field_index.php
 *
 * Lookup mode — print where one field name is defined, without storing
 * usage locations in the index file:
 *   php tools/script/build_field_index.php --where field_name
 *
 * The index is deliberately a bare sorted list of known field names so it
 * stays small and cheap to read. Check it FIRST before creating any new
 * field name; when a name already exists, the same name must keep the same
 * meaning everywhere (canonical field contract, Shared Project Standards
 * section 10.11). Use lookup mode to find where an existing name is defined.
 * Regenerate the index in the same change whenever a taxonomy JSON file or a
 * PHP structure guide adds, renames, or removes a field.
 */

$repo = dirname(__DIR__, 2);
$index = []; // field_name => list of source strings

$add = function (string $name, string $entry) use (&$index): void {
    $index[$name][] = $entry;
};

// 1. Shared taxonomy field definitions
foreach (glob("$repo/data/taxonomy/shared/*.json") as $f) {
    $records = json_decode(file_get_contents($f), true);
    foreach ($records as $r) {
        $add($r['field_name'], 'shared-taxonomy: data/taxonomy/shared/' . basename($f));
    }
}

// 2. Massage Nexus taxonomy field definitions
foreach (glob("$repo/data/taxonomy/massage_nexus/*.json") as $f) {
    if (str_contains($f, 'massage_technique_framework')) {
        continue; // framework reference records, not field definitions
    }
    $records = json_decode(file_get_contents($f), true);
    foreach ($records as $r) {
        $add($r['field_name'], 'mn-taxonomy: data/taxonomy/massage_nexus/' . basename($f));
    }
}

// 3. Collection and embedded-item fields from PHP structure-guide *_field_order arrays.
// A guide may define more than one order array when the collection contains
// bounded embedded objects; every stored field name still belongs in the
// canonical index.
foreach (glob("$repo/data/structure_guide/*.php") as $f) {
    $srcText = file_get_contents($f);
    if (preg_match_all('/\$[A-Za-z0-9_]+_field_order\s*=\s*\[(.*?)\];/s', $srcText, $matches)) {
        foreach ($matches[1] as $fieldOrder) {
            preg_match_all("/'([A-Za-z0-9_]+)'/", $fieldOrder, $mm);

            foreach ($mm[1] as $name) {
                $add($name, 'collection: data/structure_guide/' . basename($f));
            }
        }
    }
}

ksort($index);

// Lookup mode
if (($argv[1] ?? '') === '--where') {
    $name = $argv[2] ?? '';
    if ($name === '') {
        fwrite(STDERR, "Usage: php tools/script/build_field_index.php --where field_name\n");
        exit(2);
    }
    if (!isset($index[$name])) {
        echo "NOT FOUND: $name (safe to define after checking labels and meanings of similar names)\n";
        exit(1);
    }
    echo $name . "\n";
    foreach (array_values(array_unique($index[$name])) as $entry) {
        echo '  ' . $entry . "\n";
    }
    exit(0);
}

// Build mode
$lines = [];
$lines[] = '# Massage Nexus Field Name Index';
$lines[] = '# Generated by tools/script/build_field_index.php - do not edit by hand; regenerate instead.';
$lines[] = '# Check this list FIRST before creating any new field name anywhere in the project.';
$lines[] = '# If a name is listed, the concept already has a definition and the same name must keep';
$lines[] = '# the same meaning everywhere (canonical field contract, Shared Project Standards 10.11).';
$lines[] = '# To find where a listed name is defined, run:';
$lines[] = '#   php tools/script/build_field_index.php --where field_name';
$lines[] = '';
foreach (array_keys($index) as $name) {
    $lines[] = $name;
}

file_put_contents("$repo/data/field_index.txt", implode("\n", $lines) . "\n");
echo 'data/field_index.txt written: ' . count($index) . " unique field names\n";
