<?php
/**
 * Build data/field_index.txt — the compact field-name lookup index.
 *
 * Run from the repository root:
 *   php tools/script/build_field_index.php
 *
 * The index lists every known field name once, with every place it is
 * defined, so a contributor or AI can check ONE small file before creating
 * a field name instead of reading every taxonomy file and structure guide.
 * Regenerate this index in the same change whenever a taxonomy JSON file or
 * a structure guide adds, renames, or removes a field.
 */

$repo = dirname(__DIR__, 2);
$index = []; // field_name => list of "kind:source" strings

$add = function (string $name, string $entry) use (&$index): void {
    $index[$name][] = $entry;
};

// 1. Shared taxonomy field definitions
foreach (glob("$repo/data/taxonomy/shared/*.json") as $f) {
    $records = json_decode(file_get_contents($f), true);
    foreach ($records as $r) {
        $add($r['field_name'], 'shared-taxonomy:' . basename($f, '.json'));
    }
}

// 2. Massage Nexus taxonomy field definitions
foreach (glob("$repo/data/taxonomy/massage_nexus/*.json") as $f) {
    if (str_contains($f, 'massage_technique_framework')) {
        continue; // framework reference records, not field definitions
    }
    $records = json_decode(file_get_contents($f), true);
    foreach ($records as $r) {
        $add($r['field_name'], 'mn-taxonomy:' . basename($f, '.json'));
    }
}

// 3. Collection fields from PHP structure guides ($<collection>_field_order arrays)
foreach (glob("$repo/docs/04-architecture/structure-guide/*.php") as $f) {
    $collection = basename($f, '.php');
    $srcText = file_get_contents($f);
    if (preg_match('/\$' . preg_quote($collection, '/') . '_field_order\s*=\s*\[(.*?)\];/s', $srcText, $m)) {
        preg_match_all("/'([A-Za-z0-9_]+)'/", $m[1], $mm);
        foreach ($mm[1] as $name) {
            $add($name, 'collection:' . $collection);
        }
    }
}

ksort($index);

$lines = [];
$lines[] = '# Massage Nexus Field Name Index';
$lines[] = '# Generated by tools/script/build_field_index.php - do not edit by hand; regenerate instead.';
$lines[] = '# Check this file FIRST before creating any new field name in a collection, taxonomy,';
$lines[] = '# structure guide, or form. If the concept already exists here under any name, reuse';
$lines[] = '# that field name; the same field name must keep the same meaning everywhere';
$lines[] = '# (canonical field contract, Shared Project Standards section 10.11).';
$lines[] = '#';
$lines[] = '# Source kinds:';
$lines[] = '#   shared-taxonomy: reusable field definition in data/taxonomy/shared/<file>.json';
$lines[] = '#   mn-taxonomy:     Massage Nexus field definition in data/taxonomy/massage_nexus/<file>.json';
$lines[] = '#   collection:      stored collection field documented in docs/04-architecture/structure-guide/<collection>.php';
$lines[] = '';
foreach ($index as $name => $entries) {
    $lines[] = $name . ' = ' . implode(' | ', array_values(array_unique($entries)));
}

file_put_contents("$repo/data/field_index.txt", implode("\n", $lines) . "\n");
echo 'data/field_index.txt written: ' . count($index) . " unique field names\n";

// Report names defined in more than one source kind or file (contract watch list)
$multi = 0;
foreach ($index as $name => $entries) {
    $unique = array_values(array_unique($entries));
    if (count($unique) > 1) { $multi++; }
}
echo "field names with multiple sources: $multi (expected for shared fields reused by collections)\n";
