<?php

return [
    'profile_overview_hint' => 'Your username is your permanent profile address. Display details are optional and blank fields are not stored.', 'current_visibility' => 'Current visibility',
    'public_profile_description' => ':name’s public Massage Nexus profile.', 'edit_profile' => 'Edit profile', 'public_roles' => 'Public roles', 'about' => 'About', 'no_biography' => 'This member has not added a biography yet.', 'pronouns' => 'Pronouns', 'profile_details' => 'Profile details', 'gender' => 'Gender', 'handedness' => 'Handedness', 'age' => 'Age', 'birthday' => 'Birthday',
    'profile_intro' => 'Build your public identity and decide what other people may see.', 'preview_profile' => 'Preview profile', 'fix_profile_errors' => 'Please correct the highlighted profile fields.', 'public_identity' => 'Public identity', 'public_identity_hint' => 'These details help people recognize your writing and community activity.', 'biography_hint' => 'Optional; when provided, use at least 20 characters.', 'personal_details' => 'Personal details and privacy', 'personal_details_hint' => 'These values are optional and are never inferred. You choose whether each is public.', 'not_set' => 'Not set', 'gender_visibility' => 'Who can see gender', 'handedness_visibility' => 'Who can see handedness', 'private' => 'Private', 'public' => 'Public', 'birth_date' => 'Birth date', 'birth_date_private' => 'Your exact birth date remains private.', 'birth_date_display' => 'Public birthday display', 'hidden' => 'Hidden', 'age_only' => 'Age only', 'month_day_only' => 'Month and day only', 'profile_visibility' => 'Overall profile visibility', 'visibility_public' => 'Public — discoverable and viewable', 'visibility_unlisted' => 'Unlisted — viewable with the link', 'visibility_private' => 'Private — only you can view it',
    'settings_intro' => 'Manage appearance, notifications, account preferences, sessions, and recognized devices.', 'fix_setting_errors' => 'Please correct the settings form.', 'account_and_region' => 'Account, language, and region', 'interface_language' => 'Interface language', 'language_rollout_note' => 'English is the only active interface language in this release.', 'time_zone' => 'Time zone', 'appearance' => 'Appearance and accessibility', 'color_mode' => 'Color mode', 'color_mode_system' => 'Follow device setting', 'color_mode_light' => 'Light', 'color_mode_dark' => 'Dark', 'color_mode_hint' => 'Controls interface brightness only. Ink & Ember and seasonal designs are separate visual themes.', 'text_size' => 'Text size', 'high_contrast' => 'Increase contrast', 'reduced_motion' => 'Reduce non-essential motion', 'notifications' => 'Notifications', 'channels' => 'Channels', 'channel_web' => 'In-app', 'channel_email' => 'Email', 'categories' => 'Categories', 'category_security' => 'Security', 'category_booking' => 'Bookings', 'category_contribution' => 'Contributions', 'digest' => 'Digest timing', 'digest_immediate' => 'Immediate', 'digest_daily' => 'Daily', 'digest_weekly' => 'Weekly', 'digest_off' => 'Off',
    'sessions' => 'Sessions', 'sessions_hint' => 'Review where your account is signed in and end access remotely.', 'sign_out_others' => 'Sign out other sessions', 'unknown_browser' => 'Unknown browser', 'active' => 'Active', 'last_active' => 'Last active :time', 'unknown' => 'Unknown', 'password' => 'Password', 'sign_out' => 'Sign out', 'no_tracked_sessions' => 'No tracked sessions. Sessions created before this feature are not retroactively identifiable.', 'session_revoked' => 'The session was signed out.', 'other_sessions_revoked' => 'All other active sessions were signed out.', 'session_ended' => 'That session has ended. Sign in again to continue.',
    'devices' => 'Recognized devices', 'devices_explanation' => 'A device is a private, coarse browser/platform label used to group sessions. It is not an invasive fingerprint and cannot sign in by itself.', 'recognized' => 'Recognized', 'not_recognized' => 'Not yet recognized', 'last_seen' => 'Last seen :time', 'device_name' => 'Device name', 'recognize' => 'Recognize', 'distrust' => 'Don’t recognize', 'no_devices' => 'No devices have been recorded yet.', 'device_recognized' => 'The device was named and recognized.', 'device_distrusted' => 'The device was distrusted and its sessions were signed out.',
    'mfa_heading' => 'Multi-factor authentication (MFA)', 'mfa_explanation' => 'MFA requires a second proof after your password, such as a time-based code from an authenticator app.', 'recovery_explanation' => 'Recovery codes are single-use backup codes for MFA. They are separate from emailed password-reset tokens.', 'not_enabled_yet' => 'Enrollment not enabled yet',
    'user_management' => 'User management', 'user_management_intro' => 'Review accounts, access roles, and active sessions with critical lockout safeguards.', 'search_users' => 'Search by username, display name, or email', 'search' => 'Search', 'user' => 'User', 'status' => 'Status', 'member_since' => 'Member since', 'no_users_found' => 'No matching users found.', 'public_profile' => 'Public profile', 'account_status' => 'Account status', 'account' => 'Account', 'membership' => 'Membership', 'activate' => 'Activate', 'suspend' => 'Suspend', 'reason_required' => 'Reason (required, at least 10 characters)', 'update_status' => 'Update status', 'self_status_guard' => 'You cannot suspend your own account.', 'assign_role' => 'Assign role', 'show_role_publicly' => 'Allow this role to appear on the public profile', 'access_assignments' => 'Access roles', 'revocation_reason' => 'Revocation reason', 'revoke' => 'Revoke', 'no_access' => 'No access roles.', 'account_status_updated' => 'Account status updated.', 'role_assigned' => 'Role assigned.', 'role_revoked' => 'Role revoked.', 'role_already_assigned' => 'That active role is already assigned.', 'cannot_suspend_self' => 'You cannot suspend your own account.', 'cannot_remove_own_founder' => 'You cannot revoke your own Founder access.', 'cannot_remove_last_founder' => 'The last active Founder role cannot be revoked.',
];
